# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7f1748b554aaff4dbc26ac58275cccb46829b72544203abbe75a797dc5c09247f2d185c2bec14847c87ed10e70e7cc6ec8fd5a59eea7420c3d4aa9810e7be60

test:
  secret_key_base: f592bb6eebc3a28930df398c05497743ef2181c5915159dfe8724e052cbc74338737067173d82269b69c5f1e300696ced95d5e9766783848db35464e27a8f0d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
